# Playbook2: Install httpd server on node and started the httpd servers using handler.

--- # Handlers 
- hosts: demo 
  become: yes
  user: ansible
  connection: ssh 
  vars:
    pkgname: httpd
  tasks:
    - name: install httpd on node machines
      yum:
        name: "{{pkgname}}"
        state: present 
      notify: start httpd 
  handlers:
    - name: start httpd 
      service:
        name: "{{pkgname}}"
        state: started
